### ISSUE TITLE
Could not find eANN trained model

### ISSUE THREAD

**Issue by sofiapuvogelvittini** [christiando/spycon#9]
Hello, thanks for this package!

I am trying to use your eANN to predict E/I connections in my data obtained from HD-MEA. I am following the notebook titled 'Use eANN'. If I understand correctly, the spycon_test should be replaced with my own data (which I already have in the form of two arrays for times and IDs).

I am using the following code:

base_methods, model_name = coninf.setup_ensemble.get_eann_coninf_dict(num_cores=4)
eANN_params = {"name": model_name, "model_path":"C:/Users/Z674223/Documents/MEA/Maxwell/eANN/data/", 
               "con_inf_dict": base_methods,}
eANN = coninf.sci_ensemble.NNEnsemble(params=eANN_params)

eANN_result = eANN.infer_connectivity(times, ids, parallel=True)

However, I encounter the following error:

TypeError                                 Traceback (most recent call last)
Cell In[83], line 1
----> 1 eANN_result = eANN.infer_connectivity(times, ids, parallel=True)

File ~\AppData\Local\anaconda3\envs\RNAseqPython\lib\site-packages\spycon\spycon_inference.py:57, in SpikeConnectivityInference.infer_connectivity(self, times, ids, pairs, parallel, **kwargs)
     55 try:
     56     num_cores = self.params.get("num_cores", 4)
---> 57     nodes, weights, stats, threshold = self._infer_connectivity_parallel(
     58         times, ids, pairs, num_cores, **kwargs
     59     )
     60 except NotImplementedError:
     61     warnings.warn(
     62         "Parallel computation not implemented. Fall back to sequential computation.",
     63         category=RuntimeWarning,
     64     )

File ~\AppData\Local\anaconda3\envs\RNAseqPython\lib\site-packages\spycon\coninf\sci_ensemble.py:420, in NNEnsemble._infer_connectivity_parallel(self, times, ids, pairs, num_cores, spycon_result_dict)
    418 for con_inf_name, con_inf in self.con_inf_dict.items():
    419     try:
--> 420         input_dict[con_inf_name] = spycon_result_dict[con_inf_name]
    421     except KeyError:
    422         print("No result provided for %s. Method runs." % con_inf_name)

TypeError: 'NoneType' object is not subscriptable

Could you help me to figure out what I may be doing wrong? Thanks!

**Comment by sofiapuvogelvittini** [comment]
In the meantime, I am trying:
for base_method_name, base_method in base_methods.items():
     result = base_method.infer_connectivity(times, ids, parallel=True)
     result.save(f'{240711_000035}_{base_method_name}', result_path)

Which works for almost all methods, except for 1.glmpp and 2.idtxl, where I got:

1.glmpp 
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\Z674223\AppData\Local\anaconda3\envs\RNAseqPython\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Z674223\AppData\Local\anaconda3\envs\RNAseqPython\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "C:\Users\Z674223\AppData\Local\anaconda3\envs\RNAseqPython\lib\site-packages\spycon\coninf\sci_glmpp.py", line 481, in _test_unit
    unit_vi = UnitModel_VI(nidx, T, unit_times, history, numpy.unique(ids_tmp))
  File "C:\Users\Z674223\AppData\Local\anaconda3\envs\RNAseqPython\lib\site-packages\spycon\coninf\sci_glmpp.py", line 78, in __init__
    self.construct_phi_matrix()
  File "C:\Users\Z674223\AppData\Local\anaconda3\envs\RNAseqPython\lib\site-packages\spycon\coninf\sci_glmpp.py", line 168, in construct_phi_matrix
    self.compute_coupling_convolution()
  File "C:\Users\Z674223\AppData\Local\anaconda3\envs\RNAseqPython\lib\site-packages\spycon\coninf\sci_glmpp.py", line 301, in compute_coupling_convolution
    h_couplings[:, nidx] = self.convolve_spk_trains(
  File "C:\Users\Z674223\AppData\Local\anaconda3\envs\RNAseqPython\lib\site-packages\spycon\coninf\sci_glmpp.py", line 316, in convolve_spk_trains
    spk_times = spk_times[spk_times < self.trange[-1]]
IndexError: index -1 is out of bounds for axis 0 with size 0
"""

and 

2.idtxl
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\Z674223\AppData\Local\anaconda3\envs\RNAseqPython\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Z674223\AppData\Local\anaconda3\envs\RNAseqPython\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "C:\Users\Z674223\AppData\Local\anaconda3\envs\RNAseqPython\lib\site-packages\spycon\coninf\sci_idtxl.py", line 242, in _test_connection_pair
    te_estimator = JidtDiscreteTE(settings)
  File "C:\Users\Z674223\AppData\Local\anaconda3\envs\RNAseqPython\lib\site-packages\idtxl\estimators_jidt.py", line 1582, in __init__
    self._start_jvm()
  File "C:\Users\Z674223\AppData\Local\anaconda3\envs\RNAseqPython\lib\site-packages\idtxl\estimators_jidt.py", line 60, in _start_jvm
    if not jp.isJVMStarted():
NameError: name 'jp' is not defined
"""

**Comment by christiando** [comment]
Hello @sofiapuvogelvittini , thanks for looking into this package. 

1. In the `glmpp` case it seems like your trange is empty. Did you make sure that your `times` are in seconds and sorted?
2. This error comes from the idtxl package. Did you get an error from this [line](https://github.com/pwollstadt/IDTxl/blob/8d3dacfabe92715e69032310dcb043d9a46d01b9/idtxl/estimators_jidt.py#L8)? Did you install the packages from requirements.txt?

**Comment by f0rthee** [comment]
Hello, thanks for this package!
I am trying to use your dataset[ren_simulation_1917_Cell1Block1_long_340_20_ei5_example.npz] included in the repository to train my model.
However, I noticed that the dataset included in the repository does not seem to have a descriptive document or details about its source.
Could you please let me know if there is any documentation available for the dataset? Additionally, I am curious about its origin—could you share where the data comes from?
Thank you for your time and for sharing your work!
